version: "2"
services:
  bot:
    container_name: rotatinglight_bot
    build: .
    environment:
      - DB_URL=mongodb://rotatinglight_mongo/rotating-light
    links:
      - mongo
  mongo:
    container_name: rotatinglight_mongo
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
volumes: 
    data: